spring:
  application:
    name: comp4651
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: sungjin122517
    password: tjdwls1225
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

