spring:
  application:
    name: comp4651
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: sungjin122517
#    password: tjdwls1225
#    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect